### ISSUE TITLE
希望能上架chrome网上应用店

### ISSUE THREAD

**Issue by adasqg** [kikyous/music.163.com#7]
每次打开chrome都弹出一个提醒让你停用这个扩展程序，感觉很烦人，感谢作者

**Comment by kikyous** [comment]
嗯, 因为没有信用卡所以有些麻烦,我会想想办法的

**Comment by FJQBT** [comment]
应用店出现了一款跟这个很相似的插件，名字叫1Player for 网易云音乐，不知道跟作者这个什么关系 @kikyous ，不过还是没这个好用

**Comment by kikyous** [comment]
1Player for 网易云音乐 我也知道，那个和我没关系  @FJQBT

**Comment by kikyous** [comment]
https://chrome.google.com/webstore/detail/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E8%BE%85%E5%8A%A9/dmidlfboljckpijkmbmolidjimmfelho?hl=zh-CN

@FJQBT @adasqg 过了这么久终于上架了，不容易啊😭

**Comment by greatghoul** [comment]
恭喜入坑，上架了就关闭 issue 么。
