### ISSUE TITLE
问下你发布到官方应用商店的流程可以说下吗？用的什么信用卡？

### ISSUE THREAD

**Issue by suhaotian** [kikyous/music.163.com#8]
之前用的招商的信用卡，不行。。。所以想请教下您..

**Comment by kikyous** [comment]
浦发青春卡 visa 版，流程很简单啊，付了款就 OK

**Comment by suhaotian** [comment]
@kikyous ok 我申请个浦发的。。。谢谢啦 :heart:

**Comment by suhaotian** [comment]
突然想起来我当初选择付款的时候，好像没有 china 这个选项，现在有了么
